config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
   resources :pages do
     get :page_parts, :on => :collection
     get :clear, :on => :collection
     member do
       post 'preview'
     end
   end
   resources :snippets
 		resources :menus do
      resources :menu_items do
        put :update_sort, :on => :collection
      end
 		end
 		resources :contacts
 	end

  namespace :cms do
    resource :sitemap, :only => "show"
  end

  root :to => 'pages#show'

end

app/views/admin/pages/_form.html.erb
<%= tb_form_errors(f.object) %>

<h4>Page Name</h4>

<div class="form-group">
  <%= f.label :name, :required => true, :style =>"display:none;", :class=>"form-label" %>
  <div class="col-lg-12">
    <%= f.text_field :name, :class => "form-control" %>
  </div>
</div>

<h4>Page Content</h4>

<div id="page_partials_form" class="formtabs tab-content">
	<ul class="formtab_buttons nav nav-tabs">
	</ul>
	<%= f.fields_for :spud_page_partials do |b| %>
		<div class="formtab tab-pane">
			<%= b.hidden_field :name, :class => "tab_name" %>
			<%= b.text_area :content, :class => "page-partial-content-editor tinymce" %>
		</div>
	<% end %>
</div>

<h4>Advanced Settings</h4>

<div class="form-group">
  <%= f.label :layout, "Template", :class=>"col-lg-2 control-label"%>
  <div class="col-lg-10">
    <%= f.select :layout, options_for_select(layout_options,@page.layout),{},{:title => "", 'data-source' => page_parts_admin_pages_path(:page => @page.id), class: 'form-control' }%>
    <span class="help-block">Use this to control the layout template to be used for this page if they are available.</span>
  </div>
</div>

<div class="form-group">
  <%= f.label :spud_page_id, "Parent Page", :class=>"col-lg-2 control-label"%>
  <div class="col-lg-10">
    <%= f.select :spud_page_id,options_for_select(SpudPage.options_tree_for_page(:filter => @page), @page.spud_page_id),{:include_blank => 'None'},{:title => "", :class=>'form-control' }%>
  </div>
</div>

<div class="form-group">
  <%= f.label :url_name, "Perma Link",:disabled => true, :class=>"col-lg-2 control-label"%>
  <div class="col-lg-10">
    <%= root_url %>
    <%= f.text_field :url_name, :title => "", :size=>20, :class=>'form-inline' %>
  </div>
  <div class="col-lg-10">
    <%= f.check_box :use_custom_url_name, :onchange => "$('#spud_page_url_name').attr('disabled',!this.checked);" %>
    <%= f.label :use_custom_url_name, 'Customize this pages url' %>
  </div>
</div>

<h4>Meta Information</h4>
<p>These fields are used to notify search engines about important keywords and the appropriate description to display in a search result.</p>
<div class="form-group">
  <%= f.label :page_title, "Page Title", :class=>"col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_field :page_title, :class=>"form-control" %>
    <span class="help-block">The page title is the most important SEO ranking factor. <a href="https://moz.com/learn/seo/title-tag" target="_blank">Learn more</a> </span>
  </div>
</div>

<div class="form-group">
  <%= f.label :meta_keywords, "Keywords", :class=>"col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_field :meta_keywords, :class=>"form-control" %>
    <span class="help-block">A Comma seperated list of keywords for search engines. Keep it short (no more than 10 keywords)</span>
  </div>
</div>

<div class="form-group">
  <%= f.label :meta_description, "Description", :class=>"col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_area :meta_description, :class=>"form-control", :rows=>3 %>
    <span class="help-block">A short description of the page. This is what appears on a search engines search result page.</span>
  </div>
</div>

<div class="form-group">
  <%= f.label :visibility, :class=>"col-lg-2 control-label" %>
  <div class="col-lg-10">
   <%= f.select(:visibility, [["Public",0],["Private",1]], {}, {class: 'form-control'})%>
  </div>
</div>

<div class="form-group">
  <%= f.label :published, "Published", class: "col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.check_box :published %>
  </div>
</div>

<div class="form-group">
  <%= f.label :notes, "Notes", class: "col-lg-2 control-label" %>
  <div class="col-lg-10">
    <%= f.text_area :notes, :class=>"form-control", :rows=>2 %>
    <span class="help-block">Have a note to make about this page while you work? Place it here for later.</span>
  </div>
</div>
<%= hidden_field_tag "preview", 0 %>

<script type="text/javascript">
  $(document).ready(tb.cms.pages.edit);
</script>

app/views/admin/pages/_page_partials_form.html.erb
<div id="page_partials_form" class="formtabs tab-content">
	<ul class="formtab_buttons nav nav-tabs">
	</ul>
	<% last_index = 0 %>
	<% spud_page_partials.each_with_index do |spud_page_partial, index| %>
		<div class="formtab tab-pane">
			<input type="hidden" class="tab_name" name="spud_page[spud_page_partials_attributes][<%= index %>][name]" value="<%= spud_page_partial.name %>" />
			<% if spud_page_partial.id %>
				<%= hidden_field_tag "spud_page[spud_page_partials_attributes][#{index}][id]", spud_page_partial.id %>
			<% end %>
			<textarea class="page-partial-content-editor tinymce" name="spud_page[spud_page_partials_attributes][<%= index %>][content]">
				<%= spud_page_partial.content %>
			</textarea>
		</div>
		<% last_index = index + 1 %>
	<% end %>
	<% remove_page_partials.each_with_index do |spud_page_partial, index| %>
		<input type="hidden" name="spud_page[spud_page_partials_attributes][<%= last_index + index %>][id]" value="<%= spud_page_partial.id %>" />
		<input type="hidden" name="spud_page[spud_page_partials_attributes][<%= last_index + index %>][_destroy]", value="1" />
	<% end %>
</div>

app/views/admin/pages/_page_row.html.erb
<tr>
  <td>
    <%= table_nesting_indicator(depth) %>
  	<%= page.name %>
  </td>
  <td><%= link_to page_path(page.url_name), page_path(page.url_name) %></td>
  <td class="table-actions">
    <%= link_to 'View', page_path(page.url_name), :class => 'btn btn-default btn-sm' %>
    <%= link_to 'Edit', edit_admin_page_path(page), :class => 'btn btn-default btn-sm' %>
    <%= link_to 'Delete', admin_page_path(page), :method => :delete, :data => {:confirm => 'Are you sure?"'}, :class => 'btn btn-danger btn-sm' %>
  </td>
</tr>
<% page.spud_pages.ordered.each do |page| %>
	<%= render :partial => 'page_row', :locals => {:depth => depth+1, :page => page} %>
<% end %>

app/views/admin/pages/edit.html.erb
<%= form_for @page,:url => admin_page_path(:id => @page.id),:html=>{:class=>"form-horizontal page_form"} do |f| %>
	<%= render :partial => "form",:locals => {:f => f} %>
    <div class="row">
		  <div class="col-lg-10 col-offset-2">
	    	<%= f.submit "Save Page", :class => "btn btn-primary btn-save" %>
	    	<%= f.submit "Preview", :class => "btn btn-info btn-preview" %> or 
	    	<%= link_to "Cancel", admin_pages_path, :class => "btn btn-default" %>
    	</div>
    </div>
<% end %>

app/views/admin/pages/index.html.erb
<% content_for :data_controls do%>
  <%=link_to "New Page",new_admin_page_path(),:class => "btn btn-primary",:title => "New Page"%>&nbsp;
<% end %>

<%= content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>URL</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @pages.each do |page| %>
          <%= render :partial => 'page_row', :locals => {:depth => 0, :page => page} %>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/admin/pages/new.html.erb
<%= form_for @page,:url => admin_pages_path(), :html => {:class => "form-horizontal page_form"} do |f| %>
  <%= render :partial => "form",:locals => {:f => f} %>
  <div class="row">
    <div class="col-lg-10 col-offset-2">
      <%= f.submit "Create Page", :class => "btn btn-primary form-btn btn-save", "data-loading-text" => "Saving..." %>
      <%= f.submit "Preview", :class => "btn btn-primary btn-preview" %> or <%=link_to "Cancel", admin_pages_path,:class => "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/admin/pages/show.html.erb
<%=content_for :head do%>
  <meta name="description" content="<%=@page.meta_description%>" />
  <meta name="keywords" content="<%=@page.meta_keywords%>" />
<% end %>

<% if !@inline.blank? %>
  <%= render :inline => @inline %>
<% end %>
<% @page.spud_page_partials.each do |page_partial| %>
  <% if page_partial.name.downcase == 'body' && Spud::Cms.yield_body_as_content_block == false %>
    <%= page_partial.content.html_safe %>
  <% else %>
    <%= content_for page_partial.name.parameterize.underscore.to_sym do %>
      <%= page_partial.content.html_safe %>
    <% end %>
  <% end %>
<% end %>