config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
   resources :pages do
     get :page_parts, :on => :collection
     get :clear, :on => :collection
     member do
       post 'preview'
     end
   end
   resources :snippets
 		resources :menus do
      resources :menu_items do
        put :update_sort, :on => :collection
      end
 		end
 		resources :contacts
 	end

  namespace :cms do
    resource :sitemap, :only => "show"
  end

  root :to => 'pages#show'

end

app/controllers/admin/snippets_controller.rb
class Admin::SnippetsController < Admin::ApplicationController
  belongs_to_app :snippets
  add_breadcrumb 'Snippets', :admin_snippets_url

  before_action :load_snippet, only: [:show, :edit, :update, :destroy]

  def index
    @snippets = SpudSnippet.order(:name).paginate page: params[:page]
    respond_with @snippets
  end

  def new
    add_breadcrumb 'New', :new_admin_snippet_url
    @snippet = SpudSnippet.new
    respond_with @snippet
  end

  def create
    add_breadcrumb 'New', :new_admin_snippet_url
    @snippet = SpudSnippet.new(snippet_params)

    @snippet.save

    respond_with @snippet, location: admin_snippets_url
  end

  def edit
    add_breadcrumb 'Edit', :edit_admin_snippet_url

    respond_with @snippet
  end

  def update
    add_breadcrumb 'Edit', :edit_admin_snippet_url
    flash[:notice] = 'Snippet saved successfully!' if @snippet.update_attributes(snippet_params)
    respond_with @snippet, location: admin_snippets_url
  end

  def destroy
    flash[:notice] = 'Snippet removed!' if @snippet.destroy
    respond_with @snippet, location: admin_snippets_url
  end

  private

  def load_snippet
    @snippet = SpudSnippet.where(id: params[:id]).first
    if @snippet.blank?
      flash[:error] = 'Snippet does not exist!'
      redirect_to(admin_snippets_url) && (return false)
    end
  end

  def snippet_params
    params.require(:spud_snippet).permit(:content, :content_processed, :format, :name)
  end

end

app/views/admin/snippets/_form.html.erb
<%= tb_form_errors(f.object)%>

<div class="form-group">
  <%= f.label :name, :required => true, :class => "control-label" %>
  <%= f.text_field :name, :title => "", :class=>"form-control" %>
</div>

<div class="form-group">
  <%= f.label :content, :required => true, :class => "control-label" %>
  <%= f.text_area :content,:style => "width:100%;", :class => 'tinymce full-width' %>
</div>

<div class="form-group">
  <%= f.submit "Save Snippet", :class => "btn btn-primary" %>
  <%= link_to "Cancel", admin_snippets_path, :class => "btn btn-default" %>
</div>

app/views/admin/snippets/edit.html.erb
<%= form_for @snippet, :url => admin_snippet_path(@snippet) do |f| %>
  <%= render :partial => "form", :locals => {:f => f} %>
<% end %>

app/views/admin/snippets/index.html.erb
<% content_for :data_controls do %>
  <%= link_to "New Snippet",new_admin_snippet_path, :class => "btn btn-primary", :title => "New Snippet" %>
<% end %>

<% content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @snippets.each do |snippet| %>
          <tr>
            <td><%= snippet.name %></td>
            <td class="table-actions">
              <%= link_to 'Edit', edit_admin_snippet_path(snippet), :class => 'btn btn-sm btn-default' %>
              <%= link_to 'delete', admin_snippet_path(snippet), :method => :delete, :class => 'btn btn-sm btn-danger', :data => {:confirm => 'Are you sure you want to delete this snippet?'} %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/admin/snippets/new.html.erb
<%= form_for @snippet, :url => admin_snippets_path do |f| %>
  <%= render :partial => "form",:locals => {:f => f} %>
<% end %>