config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
   resources :pages do
     get :page_parts, :on => :collection
     get :clear, :on => :collection
     member do
       post 'preview'
     end
   end
   resources :snippets
 		resources :menus do
      resources :menu_items do
        put :update_sort, :on => :collection
      end
 		end
 		resources :contacts
 	end

  namespace :cms do
    resource :sitemap, :only => "show"
  end

  root :to => 'pages#show'

end

app/controllers/admin/menu_items_controller.rb
class Admin::MenuItemsController < Admin::ApplicationController
  add_breadcrumb 'Menus', :admin_menus_path
  belongs_to_app :menus, page_title: 'Menu Items'
  before_action :load_menu
  before_action :load_menu_item, only: [:edit, :update, :show, :destroy, :reorder]

  def index
    @menu_items = @menu.spud_menu_items.order(:menu_order).includes(:spud_menu_items)
    respond_with @menu_items
  end

  def new
    add_breadcrumb 'New', :new_admin_page_path

    @menu_item = @menu.spud_menu_items.new
    respond_with @menu_item
  end

  def create
    add_breadcrumb 'New', :new_admin_page_path
    @menu_item = SpudMenuItem.new(menu_item_params)
    @menu_item.spud_menu_id = @menu.id
    if params[:spud_menu_item][:parent_id].blank?
      @menu_item.parent_id = @menu.id
      @menu_item.parent_type = 'SpudMenu'
    else
      @menu_item.parent_type = 'SpudMenuItem'
    end
    if @menu_item.name.blank? && !@menu_item.spud_page.blank?
      @menu_item.name = @menu_item.spud_page.name
    end
    if @menu_item.menu_order.blank?
      highest_sibling = @menu_item.parent.spud_menu_items.order('menu_order desc').first
      unless highest_sibling.blank?
        @menu_item.menu_order = highest_sibling.menu_order + 1
      end
    end
    flash[:notice] = 'Menu Created successfully!' if @menu_item.save

    respond_with @menu_item, location: admin_menu_menu_items_url
  end

  def edit
    add_breadcrumb "Edit #{@menu_item.name}", :edit_admin_menu_menu_item_path
    @menu_item.parent_id = nil if @menu_item.parent_type == 'SpudMenu'
    respond_with @menu_item
  end

  def update
    add_breadcrumb "Edit #{@menu_item.name}", :edit_admin_menu_menu_item_path
    if params[:spud_menu_item][:parent_id].blank?
      params[:spud_menu_item][:parent_type] = 'SpudMenu'
      params[:spud_menu_item][:parent_id] = @menu.id
    else
      params[:spud_menu_item][:parent_type] = 'SpudMenuItem'
    end
    @menu_item.attributes = menu_item_params()
    @menu_item.spud_menu_id = @menu.id
    flash[:notice] = 'Menu saved successfully!' if @menu_item.save

    respond_with @menu_item, location: admin_menu_menu_items_url
  end

  def destroy
    flash[:notice] = 'Menu Item removed!' if @menu_item.destroy

    respond_with @menu_item, location: admin_menu_menu_items_url
  end

  def update_sort
    params[:order]&.each_with_index do |item, index|
      val = item.to_i
      menu_item = @menu.spud_menu_items.find_by(id: val)
      menu_item.menu_order = index
      menu_item.save
    end
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def load_menu
    @menu = SpudMenu.where(id: params[:menu_id]).first

    if @menu.blank?
      flash[:error] = 'Menu not found!'
      redirect_to(admin_menus_url()) && (return false)
    end
    add_breadcrumb @menu.name.to_s, :admin_menu_menu_items_path
  end

  def load_menu_item
    @menu_item = SpudMenuItem.where(id: params[:id]).first
    if @menu_item.blank?
      flash[:error] = 'Menu Item not found!'
      redirect_to(admin_menu_menu_items_url()) && (return false)
    end
  end

  def menu_item_params
    params.require(:spud_menu_item).permit(:name, :parent_type, :parent_id, :item_type, :spud_page_id, :menu_order, :url, :classes)
  end

end

app/views/admin/menu_items/_form.html.erb
<%= tb_form_errors(f.object)%>

<div class="form-group">
	<%= f.label :name, :required=>true, :class=>"col-sm-2 control-label" %>
	<div class="col-sm-10">
		<%= f.text_field :name, :title => "", :class=>"form-control" %>
	</div>
</div>

<div class="form-group">
	<%=f.label :menu_order, :required=>true,:class => "col-sm-2 control-label"%>
	<div class="col-sm-10">
		<%=f.text_field :menu_order, :title => "", :class=>'form-control'%>
	</div>
</div>

<div class="form-group">
	<%=f.label :spud_page_id, "Page", :class=>"col-sm-2 control-label"%>
	<div class="col-sm-10">
		<%=	f.select :spud_page_id,	options_for_select(SpudPage.options_tree_for_page(), @menu_item.spud_page_id), {:include_blank => 'Use URL instead'}, {:class=>'form-control',:title => "", :onchange => "if($(this).val() != '') {$('#spud_menu_item_url').val('');}"}%>
	</div>  
</div>

<div class="form-group">
	<%=f.label :url, :class => "col-sm-2 control-label"%>
	<div class="col-sm-10">
		<%=f.text_field :url, :title => "", :class=>'form-control' %>
	</div>
</div>

<div class="form-group">
	<%=f.label :classes, :class => "col-sm-2 control-label"%>
	<div class="col-sm-10">
		<%=f.text_field :classes, :title => "", :class=>'form-control'%>
	</div>
</div>

<div class="form-group">
	<%= f.label :parent, "Parent Menu", :class=>"col-sm-2 control-label" %>
	<div class="col-sm-10">
		<%=f.select :parent_id,options_for_select(SpudMenuItem.options_tree_for_item(@menu,:filter => @menu_item),@menu_item.parent_type == 'SpudMenuItem' ? @menu_item.parent_id : nil),{:include_blank => "#{@menu.name}"},{:class => 'form-control', :title => ""}%>
	</div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Save Menu Item", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_menu_menu_items_path, :class => "btn btn-default" %>
  </div>
</div>

app/views/admin/menu_items/_menu_item_row.html.erb
<tr>
	<td>
		<%= table_nesting_indicator(depth) %>
		<%= menu_item.name %>
	</td>
	<td><%= link_to menu_item.get_url, menu_item.get_url %></td>
	<td class="table-actions">
		<%=link_to 'Edit', edit_admin_menu_menu_item_path(:id => menu_item.id), :title => "Edit Menu Item", :class => 'btn btn-default btn-sm' %>
		<%=link_to 'Delete', admin_menu_menu_item_path(:id => menu_item.id), :method => :delete, :class => 'btn btn-danger btn-sm', :data => {:confirm => "Are you sure you want to remove this menu item?"} %>
	</td>
	<input type="hidden" value=<%= menu_item.id %>>
</tr>
<% menu_item.spud_menu_items.each do |item| %>
  <%= render :partial => 'menu_item_row', :locals => {:menu_item => item, :depth => depth+1} %>
<% end %>

app/views/admin/menu_items/edit.html.erb
<%= form_for @menu_item, :url => admin_menu_menu_item_path(:id => @menu_item.id), :html => {:class=>"form-horizontal"} do |f| %>
  <% render :partial => "form",:locals => {:f => f}%>
<% end %>

app/views/admin/menu_items/index.html.erb
<% content_for :data_controls do %>
  <%= link_to "New Menu Item", new_admin_menu_menu_item_path(), :class => "btn btn-primary", :title => "New Menu Item" %>
<% end %>

<% content_for :detail do %>
  <div id="sort" class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>URL</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @menu_items.each do |item| %>
          <%= render :partial => 'menu_item_row', :locals => {:menu_item => item, :depth => 0} %>
        <% end %>
      </tbody>
    </table>
    <input type="hidden" value=<%= @menu.id %> id="menu-id">
  </div>
<script type="text/javascript">
  $(document).ready(tb.cms.menu_items.init);
</script>

<% end %>

app/views/admin/menu_items/new.html.erb
<%= form_for @menu_item, :url => admin_menu_menu_items_path, :html => {:class=>"form-horizontal"} do |f| %>
  <%= render :partial => "form",:locals => {:f => f} %>
<% end %>