config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
   resources :pages do
     get :page_parts, :on => :collection
     get :clear, :on => :collection
     member do
       post 'preview'
     end
   end
   resources :snippets
 		resources :menus do
      resources :menu_items do
        put :update_sort, :on => :collection
      end
 		end
 		resources :contacts
 	end

  namespace :cms do
    resource :sitemap, :only => "show"
  end

  root :to => 'pages#show'

end

app/controllers/admin/menus_controller.rb
class Admin::MenusController < Admin::ApplicationController
  belongs_to_app :menus
  add_breadcrumb 'Menus', :admin_menus_path
  before_action :load_menu, only: [:edit, :update, :show, :destroy]

  def index
    @menus = SpudMenu.all.paginate(page: params[:page])
    respond_with @menus
  end

  def new
    add_breadcrumb 'New', :new_admin_menu_path
    @menu = SpudMenu.new
    respond_with @menu
  end

  def create
    add_breadcrumb 'New', :new_admin_menu_path
    @menu = SpudMenu.new(menu_params)
    flash[:notice] = 'New menu created' if @menu.save
    respond_with @menu, location: !@menu.id.nil? ? admin_menu_menu_items_url(menu_id: @menu.id) : admin_menus_url
  end

  def edit
    add_breadcrumb "Edit #{@menu.name}", :edit_admin_menu_path
    respond_with @menu
  end

  def update
    add_breadcrumb "Edit #{@menu.name}", :edit_admin_menu_path

    flash[:notice] = 'Menu saved successfully' if @menu.update_attributes(menu_params)
    respond_with @menu, location: admin_menu_menu_items_url(menu_id: @menu.id)
  end

  def destroy
    flash[:notice] = 'Menu removed!' if @menu.destroy
    respond_with @menu, location: admin_menus_url
  end

  private

  def load_menu
    @menu = SpudMenu.where(id: params[:id]).first
    if @menu.blank?
      flash[:error] = 'Menu not found!'
      redirect_to(admin_menus_url()) && (return false)
    end
  end

  def menu_params
    params.require(:spud_menu).permit(:name)
  end

end

app/views/admin/menus/_form.html.erb
<%=tb_form_errors(f.object)%>

<div class="form-group">
  <%= f.label :name, nil, :class=>"col-sm-2 control-label" %>
  <div class="col-sm-10">
    <%= f.text_field :name, :class => "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit "Save Menu", :class => "btn btn-primary" %>
    <%= link_to "Cancel", admin_menus_path, :class => "btn btn-default" %>
  </div>
</div>

app/views/admin/menus/edit.html.erb
<%=form_for @menu,:url => admin_menu_path(:id => @menu.id),:html=>{:class=>"form-horizontal"} do |f|%>
  <%= render :partial => "form",:locals => {:f => f} %>
<% end %>

app/views/admin/menus/index.html.erb
<% content_for :data_controls do%>
	<%= link_to "New Menu", new_admin_menu_path(), :class => "btn btn-primary", :title => "New Menu" %>
<% end %>

<% content_for :detail do %>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th># Items</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <% @menus.each do |menu| %>
          <tr>
            <td><%= menu.name %></td>
            <td><%= menu.spud_menu_items.count %></td>
            <td class="table-actions">
              <%= link_to 'Items', admin_menu_menu_items_path(:menu_id => menu.id), :class => 'btn btn-default btn-sm' %>
              <%= link_to 'Edit', edit_admin_menu_path(:id => menu.id), :class => 'btn btn-default btn-sm' %>
              <%= link_to 'Delete', admin_menu_path(:id => menu.id), :method => :delete, :data => {:confirm => 'Are you sure?"'}, :class => 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate @menus, :renderer => BootstrapPagination::Rails %>
<% end %>

app/views/admin/menus/new.html.erb
<%= form_for @menu,:url => admin_menus_path,:html=>{:class=>"form-horizontal"} do |f| %>
  <%= render :partial => "form",:locals => {:f => f} %>
<% end %>